BungeePlayer:
  Debug:
    Events: false
    Packets: false
    WatchDog: false
    BungeePlayerCommand: false
  SupportedProtocols:
    - 316
    - 315
    - 210
    - 110
    - 109
    - 108
    - 107